vim.opt.guicursor = ""
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.updatetime = 50
vim.opt.colorcolumn = "80"
vim.o.timeout = true   -- Make sure timeout is enabled
vim.o.timeoutlen = 300 -- Set timeout for mapped key sequences (e.g., 300ms). You can test with 100ms or 500ms.
vim.o.ttimeout = true  -- Make sure key code timeout is enabled
vim.o.ttimeoutlen = 50
